### PR TITLE
U4X-591 : Separate DOT from TB follow up form

### PR DESCRIPTION
**Pull request by jabahum**
https://metsprogramme.atlassian.net/browse/U4X-591

### CODE REVIEW

**Comment by slubwama** [comment]
@jabahum  would you care to also update the HFE the same way

**Comment by jabahum** [comment]
> @jabahum would you care to also update the HFE the same way

Let me get to this

**Comment by slubwama** [comment]
@jabahum  resolve conflicts

**Comment by slubwama** [comment]
@jabahum  resolve conflicts

**Comment by slubwama** [comment]
@jabahum closing this given that it has taken a long time without merging.

**Pull request closed without merging**
