### PR TITLE
TB Follow up form failing to save Fix

### PR DESCRIPTION
**Pull request by dbaluku**

### CODE REVIEW

**Review by jabahum — CHANGES_REQUESTED** [review]
Can we remove  section for Community Follow up

**Comment by slubwama** [comment]
> Can we remove section for Community Follow up

@dbaluku add ticket for this PR.

**Comment by slubwama** [comment]
> Can we remove section for Community Follow up

@jabahum  is there any thing attacked to community followup on this PR

**Comment by slubwama** [comment]
@dbaluku  I am closing this given that its been over taken by events

**Pull request closed without merging**
