### PR TITLE
added concepts for Clinical management form

### PR DESCRIPTION
**Pull request by Mwanje**

### CODE REVIEW

**Comment by semujju** [comment]
1. Add YES/NO to Digital Capillary Refill time > 2 (166408)
2. Create concept for "Confusion" add it to Daily Clinical Features (166413)
3. Create lab tests "AST/SGOT, Creatine and Kinase" and add them to (166336)
4. Add concepts for APTT/APTR (166329), PT(166330), INR (166331), Creatinine (790) to (166336)
5. Add YES/NO/UNKNOWN to Chest X-ray (12)
6. Create concept for "Infiltrates Present" add YES/NO/UNKNOWN 
7. Add YES/NO to oral Liquid (165578)
8. Remove Vitamin C Deficiency and Zinc Sulphate from supportive treatment (166346) add concept for vitamin C (71589)
9. Create concept for "Zinc" add it to (166346)
10. Change Antibiotics (1195) to coded and add YES/NO
11. Add YES/NO to Hydroxychloroquine (166348)
12. Add YES/NO/UNKNOWN to Antiviral (166351)
13. Add YES/NO/UNKNOWN to Corticosteroid (166353)
14. Rename Hydrocortison to Hydrocortisone/Other
15. Add "Oral, Intravenous, Inhaled" to route (166352) and remove them from corticosteroid (166353)
16. Add YES/NO to blood gas done (166405), and it shouldn`t be numeric
17. Create concept for "Other Daily Clinical Features" make it text add it to (166413)
18. Create >15 L/min add it to 02 flow (166395)
19. Add "Cardiac Arrest, Liver Dysfunction" to Complications (166378) and give them answers YES/NO/UNKNOWN
20. Add YES/NO/UNKNOWN to severe dehydration (166406), remove text data type
21. Add Temperature (5088), Heart Rate (5087), Respiratory Rate (5242), Diasytolic (5085), Systolic (5086), GCS/15 (166407), Oxygen Saturation (5092) to Covid Vitals (166411)
22. Rename AUPU (166410) to AVPU

**Comment by semujju** [comment]
Change datatype for comorbidity to coded(2)
Create concept for countries traveled (text)

**Comment by semujju** [comment]
- Rename "travel status -166322 "  to "traveled out of town"
- Create concept for travel history and attach 166322, 166301, 166302, 166321, 166320
- Add district (165853), Country (165929) to domestic travel (166298)
- Add Countries traveled (new) to International travel (166299)

**Comment by semujju** [comment]
Add pregnant (90041) to underlying conditions (166293)
Add post partum (166291), breast feeding (99601), gestation age (162983) , Trimester (166292) to pregnant (90041)

**Comment by semujju** [comment]
@Mwanje confirm these concepts from your server. I can not find them on my side.
- Create lab tests "AST/SGOT, Creatine and Kinase" and add them to (166336)
- **Add YES/NO to oral Liquid (165578)**
- **Change Antibiotics (1195) to coded and add YES/NO**
- To Hydrocortisone/Other (166419) add YES/NO
- Remove "Oral, Intravenous, Inhaled" from corticosteroid (166353)
- Add Heart Rate (5087), to Covid Vitals (166411)
- Add "Confusion (90105)" to Daily Clinical Features (166413)
- Add Other cormobidity (166297) to Cormobidity (166319)
- Remove cormobidity (166254) from concepts

**Comment by semujju** [comment]
For concept_id = 162943, change creator = 2 to creator = 1
For Digital Capillary Refill time > 25 use Digital Capillary Refill time &gt;2s
Find concept_answer_ids = 7367735, 7367736, 7367737 and change creator = 3 to  creator = 1

**Comment by semujju** [comment]
Add Yes, No, Unknown to 1367 (On ART)
Add Yes, No, Unknown to  162306 (NSAID)
Add Yes, No, Unknown to 162307 (Statin)
Use &gt;15 for (166416)
Change 1195 from N/A to coded
**Change 90190 (ALT/SGPT) from N/A to numeric data type** 
Add Yes, No to 166359 (Anticoagulation)
Create concept for specify Anticoagulation add it to 166359 (Anticoagulation)

**> Create concept for other treatment of other comorbidities (text)**

**Comment by semujju** [comment]
Add Yes, No, Unknown to (112989, 166372, 206, 147241, 115835, 166373, 121629, 166374, 120148, 166375, 166376, 114100, 147, 5016, 166371)

**Comment by Mwanje** [comment]
> Add Yes, No, Unknown to 1367 (On ART)
> Add Yes, No, Unknown to 162306 (NSAID)
> Add Yes, No, Unknown to 162307 (Statins)
>Change 1195 from N/A to coded

for these concepts that already exist, we still need to figure out a way of editing their data types since I could not find them in the custom concept file

**Comment by Mwanje** [comment]
> Add Yes, No, Unknown to (112989,  206, 147241, 121629, 120148, 114100, 147, 5016)
I cant find them in the custom concept file for editing

**Comment by Mwanje** [comment]
> * Change Antibiotics (1195) to coded and add YES/NO

not found in the custom concept file

**Pull request merged**
