### PR TITLE
ART Regimen Line Fixes 

### PR DESCRIPTION
**Pull request by ssmusoke**
1. Added 'No Current Regimen' text when the user has no current regimen
2. Removed the check for the ART Clinical Assessment page especially true for Transfer Ins - https://app.asana.com/0/0/1201344216027189/f
3. Display the Transfer IN regimen when the Current Regimen is not provided https://app.asana.com/0/0/1201344216027186/f
4. Updated the list of transfer in concept answers to match the current regimen https://app.asana.com/0/1133167201254915/1201357057327111/f
4. Changed the new Regimen line to show the next regimen line only not multiple options

https://app.asana.com/0/1133167201254915/1200982225552130

Before 
Screen Shot 2021-09-14 at 15 23 35

After 
Screen Shot 2021-09-14 at 19 40 42

### CODE REVIEW

**Comment by slubwama** [comment]
@ssmusoke Even a patient with a current regimen the Current regimen section still has **"No Current Regimen"**. There is still work on this one. todo

**Comment by ssmusoke** [comment]
@slubwama remember the check is date based, make sure your encounter date is after the date of the clinical assessment with the current Regimen

**Comment by slubwama** [comment]
@ssmusoke not in this PR. But there is a wrong redirection on the Regimen switch where its looking out for clinical assessment instead of the summary page

   <ifMode mode="ENTER,EDIT" include="false">
        <includeIf velocityTest="$fn.allEncounters('8d5b27bc-c2cc-11de-8d13-0010c6dffd0f').size() == 0 or $fn.allEncounters('8d5b2be0-c2cc-11de-8d13-0010c6dffd0f').size() == 0">
            <script>
                jq(function () {
                    jq().toastmessage('showErrorToast', "This patient is missing an ART Summary page and a Clinical Assessment page");
                    alert('This patient has no Summary page, you will now be forwarded to the patient dashboard');

**Comment by ssmusoke** [comment]
@slubwama The check is for both the Summary and Clinical Assessment pages - as you cannot have a switch without the two done at least once

**Pull request merged**
